.TH YED-LANG-SYNTAX-RV64iASM 7 "YED Plugin Manuals" "" "YED Plugin Manuals"
.SH NAME
lang/syntax/rv64asm \- Syntax highlighting for the RISCV 64i Assembly filetype.
.SH CONFIGURATION
None
.SH COMMANDS
None
.SH BUFFERS
None
.SH NOTES
None
.SH VERSION
None
1000.\&01
.SH KEYWORDS
lang, language, filetype, file, syntax, highlight, assembly
